# Generated by Django 4.1.1 on 2022-09-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="myTodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=80)),
                ("priority", models.IntegerField()),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("deadline", models.DateField(null=True)),
            ],
        ),
    ]
