# Generated by Django 4.1.1 on 2022-09-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_mytodo_bt"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytodo_bt",
            name="id_2",
            field=models.IntegerField(default=0),
        ),
    ]
